name: anki

services:
  sync-server:
    image: phbjdocker/anki-sync-server
    volumes:
      - sync-data:/home/anki
    ports:
      - 8080:8080
    environment:
      - PASSWORDS_HASHED=1
      - SYNC_USER1=${ANKI_USER}:${ANKI_PASSWORD}
    restart: always
volumes:
  sync-data:
