name: Build Docker Image of Anki Sync Server
on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        type: string
        description: "Version of Anki, e.g., 24.06.3"

env:
  anki_upstream_repo: ankitects/anki
  anki_source_path: anki
  anki_sync_port: 8080
  docker_image_name: anki-sync-server

jobs:
  checkout:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out Anki Source Code
        uses: actions/checkout@v4
        with:
          repository: ${{ env.anki_upstream_repo }}
          ref: ${{ github.event.inputs.version }}
          path: ${{ env.anki_source_path }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ${{ env.anki_source_path }}
          file: ${{ env.anki_source_path }}/docs/syncserver/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.docker_image_name }}:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.docker_image_name }}:${{ github.event.inputs.version }}
          build-args: |
            ANKI_VERSION=${{ github.event.inputs.version }}
            SYNC_PORT=${{ env.anki_sync_port }}
