name: Build Docker Image of Anki Sync Server Daily
on:
  schedule:
    # Run at 0:00 UTC every Tuesday
    - cron: '0 0 * * 2'
  workflow_dispatch:

env:
  anki_upstream_repo: ankitects/anki
  anki_upstream_branch: main
  anki_source_path: anki
  docker_image_name: anki-sync-server
  docker_image_tag: weekly

jobs:
  checkout:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out Anki Source Code
        uses: actions/checkout@v4
        with:
          repository: ${{ env.anki_upstream_repo }}
          ref: ${{ env.anki_upstream_branch }}
          path: ${{ env.anki_source_path }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ${{ env.anki_source_path }}
          file: ${{ env.anki_source_path }}/docs/syncserver/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.docker_image_name }}:${{ env.docker_image_tag }}
